name: HTML & CSS Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # HTML linter
      - name: Lint HTML
        uses: Cyb3r-Jak3/html5validator-action@v1
        with:
          root: .

      # CSS linter
      - name: Lint CSS
        run: |
          npm install -g stylelint stylelint-config-standard
          stylelint "**/*.css"
